
baseURL = "https://nicolas.boulard.family/"
title = "Nicolas Boulard"
theme = "hugo-coder"
languageCode = "fr-fr"
defaultContentLanguage = "fr-fr"
paginate = 20
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
author = "Nicolas Boulard"
info = ["Ing√©nieur cloud & DevOps", "Amateur de montagne üèîÔ∏è"]
description = "Nicolas Boulard ing√©nieur cloud & devops, je suis un passionn√© de sport et de montagne, un peu geek aussi j'aime d√©couvrir par moi m√™me les technologies qui gravitent autour du cloud"
keywords = "blog,developpeur,dev,ops,devops,cloud,personal,montagne,grimpeur,alpinisme"
avatarURL = "images/avatar.jpg"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2023
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
# outboundLinksTracking = true
# fileDownloadsTracking = true

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to use Yandex Metrika(https://metrika.yandex.ru) for analytics, add this section
# [params.yandexMetrika]
# id = "gid"

# If you want to use Application Insights(https://azure.com/) for analytics, add this section
# [params.applicationInsights]
# connectionString = "connectionString"

# If you want to use microanalytics.io for analytics, add this section
# [params.microAnalytics]
# id = "ABCDE"
# dnt = "false" # respect DNT tracker, "true" by default

# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'", "https://www.youtube.com"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/",
# ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive ‚Äì defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/NicolasBoulard/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/nicolas-boulard/"


[[languages.fr-fr.menu.main]]
name = "√Ä propos"
weight = 1
url = "about/"

[[languages.fr-fr.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.fr-fr.menu.main]]
name = "Projets"
weight = 3
url = "projects/"

[[languages.fr-fr.menu.main]]
name = "Contact"
weight = 5
url = "contact/"
